---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jobsched-api
spec:
  rules:
    - host: services-dev.com
      http:
        paths:
          - path: /api/jobsched/v1
            backend:
              serviceName: jobsched-api
              servicePort: 80
