---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jobsched-api
rules:
  - apiGroups: [ policy ]
    resources: [ podsecuritypolicies ]
    verbs: [ use ]
    resourceNames: [ jobsched-api ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jobsched-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobsched-api
subjects:
  - kind: ServiceAccount
    name: jobsched-api
